apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: default-v1beta1
spec:
  weight: 15
  disruption:
      consolidationPolicy: WhenUnderutilized
  template:
    spec:
      kubelet:
        systemReserved:
          cpu: 100m
      nodeClassRef:
        apiVersion: karpenter.k8s.aws/v1beta1
        kind: EC2NodeClass
        name: default
      requirements:
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values:
          - c
          - m
          - r
        - key: karpenter.k8s.aws/instance-size
          operator: NotIn
          values:
          - nano
          - micro
          - small
          - medium
          - large
        - key: karpenter.k8s.aws/instance-size
          operator: In
          values:
          - 4xlarge
          - xlarge
        - key: karpenter.sh/capacity-type
          operator: In
          values:
          - spot
          - on-demand
        - key: karpenter.k8s.aws/instance-hypervisor
          operator: In
          values:
          - nitro
        - key: kubernetes.io/os
          operator: In
          values:
          - linux
        - key: kubernetes.io/arch
          operator: In
          values:
          - amd64
---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2
  role: karpenter-shared-role
  tags:
    testing: interruptMe
  securityGroupSelectorTerms:
  - tags:
      karpenter.sh/discovery: ${CLUSTER_NAME}
  subnetSelectorTerms:
  - tags:
      karpenter.sh/discovery: ${CLUSTER_NAME}